import { CurrentDashboardAction, RetrieveDashboardsAction } from './dashboard';

export enum Types {
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAIL = 'REGISTER_FAIL',
  MEMBER_LOADED = 'MEMBER_LOADED',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  AUTH_ERROR = 'AUTH_ERROR',
  LOGOUT = 'LOGOUT',
  GET_DASHBOARD = 'GET_DASHBOARD',
  GET_DASHBOARDS = 'GET_DASHBOARDS',
  DASHBOARD_ERROR = 'DASHBOARD_ERROR',
  CLEAR_MEMBER = 'CLEAR_MEMBER',
  GET_GROUPS = 'GET_GROUPS',
  GROUP_ERROR = 'GROUP_ERROR',
  GET_GROUP = 'GET_GROUP',
  GET_POST = 'GET_POST',
  UPDATE_UPVOTES = 'UPDATE_UPVOTES',
  ADD_POST = 'ADD_POST',
  POST_ERROR = 'POST_ERROR',
  ADD_COMMENT = 'ADD_COMMENT',
  CREATE_GROUP = 'CREATE_GROUP',
  UPVOTE_POST = 'UPVOTE_POST',
  CLEAR_POST = 'CLEAR_POST',
  CLEAR_GROUP = 'CLEAR_GROUP',
}

export type Action = CurrentDashboardAction | RetrieveDashboardsAction;
